---

# Internally, we expose 'web' onto the same FQDN as externally, but the name
# will be resolved to the private IPs bu BOSH DNS, acting as a BOSH-native
# 'split DNS' feature.

- path: /instance_groups/name=web/jobs/name=web/custom_provider_definitions?/name=web-address
  type: replace
  value:
    name: web-address
    type: address

- path: /instance_groups/name=web/jobs/name=web/provides?/web-address
  type: replace
  value:
    shared: true
    aliases:
      - domain: ((external_host))
        health_filter: smart

- path: /instance_groups/name=uaa/jobs/name=uaa/provides/uaa-address/shared?
  type: replace
  value: true

- path: /instance_groups/name=credhub/jobs/name=credhub/provides/credhub-address/shared?
  type: replace
  value: true


# Externally, 'web' is exposed onto the Traefik reverse proxy.

- path: /instance_groups/name=web/jobs/name=web/properties/external_url
  type: replace
  value: https://((external_host))

- path: /instance_groups/name=web/jobs/name=web/properties/tls/bind_port?
  type: replace
  value: ((atc_tls_bind_port))


- path: /instance_groups/name=web/jobs/name=web/properties/x_frame_options?
  type: replace
  # Prevent clickjacking attacks
  # See <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options>
  # See <https://en.wikipedia.org/wiki/clickjacking>
  value: DENY
