#!/usr/bin/env bash

set -eo pipefail

function main() {
    setup

    # Global variables, so that the cleanup() exit function can access these:
    concourse_target=${1:-"ef"}
    pipeline_name=self-sanity-tests

    set -x

    (
        set +e
        if ! fly -t "${concourse_target}" status; then
            bash ${DEBUG:+"-x"} "${SUBSYS_DIR}/fly-login" "${concourse_target}"
        fi
    )

    set +x
    source <("${SUBSYS_DIR}/credhub-env")
    set -x

    echo "Checking correct authentication to Credhub."
    local secrets_found
    secrets_found=$(
        credhub find --output-json \
            | jq --raw-output '.credentials | length'
    )
    echo "OK: ${secrets_found} secrets found"

    trap cleanup EXIT

    credhub set --name "/concourse/main/team-var"                      --type "value" --value "plip"
    credhub set --name "/concourse/main/${pipeline_name}/pipeline-var" --type "value" --value "plop"

    credhub get --name "/concourse/main/team-var"
    credhub get --name "/concourse/main/${pipeline_name}/pipeline-var"

    (
        set +x
        credhub set --name "/concourse/main/${pipeline_name}/harbor-admin-password" --type "value" \
            --value "$(harbor_creds_var "/harbor_admin_password")"
        credhub set --name "/concourse/main/${pipeline_name}/credhub-ca-cert" --type "value" \
            --value "${CREDHUB_CA_CERT}"
    )

    local external_domain  harbor_fqdn
    external_domain=$(priv_cfg_var "/external_domain")
    harbor_fqdn="harbor.${external_domain}"
    fly --target="${concourse_target}" set-pipeline --non-interactive \
        --pipeline="${pipeline_name}" \
        --config=<(pipeline_definition) \
        --var="registry_prefix=${harbor_fqdn}/" \
        --var="credhub_fqdn=credhub.${external_domain}" \
        --var="credhub_server=${CREDHUB_SERVER}"

    fly --target="${concourse_target}" unpause-pipeline \
        --pipeline="${pipeline_name}"

    fly --target="${concourse_target}" trigger-job --watch \
        --job="${pipeline_name}/test-job"
}

function setup() {
    SUBSYS_DIR=${SUBSYS_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}
    BASE_DIR=${BASE_DIR:-$(git rev-parse --show-toplevel)}
    readonly SUBSYS_DIR BASE_DIR
}

function cleanup() {
    if [[ -z ${concourse_target} || -z ${pipeline_name} ]]; then
        echo "ERROR: missing 'concourse_target' or 'pipeline_name' info for proper cleanup." \
            "Aborting cleanup."
        return
    fi
    fly -t "${concourse_target}" destroy-pipeline -n -p "${pipeline_name}" > /dev/null

    credhub delete --name "/concourse/main/team-var"
    credhub delete --name "/concourse/main/${pipeline_name}/pipeline-var"
    credhub delete --name "/concourse/main/${pipeline_name}/harbor-admin-password"
    credhub delete --name "/concourse/main/${pipeline_name}/credhub-ca-cert"
}

function pipeline_definition() {
    cat <<'EOF'
---
resources:
  - name: test-resource
    type: time
    source:
      interval: 1m

  - name: test-image
    type: docker-image
    source:
      repository: ((registry_prefix))gstack/gk-ops
      username: admin
      password: ((harbor-admin-password))

jobs:
  - name: test-job
    plan:
      - get: test-resource
      - get: test-image
      - task: test-task
        image: test-image
        config:
          platform: linux
          params:
            TEAM_VAR: ((team-var))
            PIPELINE_VAR: ((pipeline-var))
            CREDHUB_SERVER: ((credhub_server))
            CREDHUB_CA_CERT: ((credhub-ca-cert))
          run:
            path: bash
            args:
              - -ec
              - |
                export TERM=xterm-256color
                error=0
                if [[ "${TEAM_VAR}" != "plip" ]]; then
                    echo >&2 "$(tput setaf 1)$(tput smso)ERROR:$(tput rmso) expected the 'team-var' variable value '((team-var))' to be 'plip'$(tput sgr0)"
                    error=$(( $error + 1 ))
                fi
                if [[ "${PIPELINE_VAR}" != "plop" ]]; then
                    echo >&2 "$(tput setaf 1)$(tput smso)ERROR:$(tput rmso) expected the 'pipeline-var' variable value '((pipeline-var))' to be 'plop'$(tput sgr0)"
                    error=$(( $error + 1 ))
                fi
                if [[ "${error}" -gt 0 ]]; then
                    exit 1
                fi
                (
                    set -x
                    host ((credhub_fqdn))
                    credhub api       # checks connectivity from workers to Credhub
                    credhub --version
                )
                echo "$(tput setaf 5)$(tput bold)Concourse rocks"\!"$(tput sgr0)"
EOF
}

function priv_cfg_var() {
    local path=$1
    bosh int "${SUBSYS_DIR}/conf/private-config.yml" --path "${path}"
}

function state_var() {
    local state_file=$1
    local path=$2
    bosh int "${BASE_DIR}/state/${SUBSYS_NAME}/${state_file}.yml" --path "${path}"
}

function harbor_creds_var() {
    SUBSYS_NAME="harbor" state_var "depl-creds" "$1"
}

main "$@"
