---

jobs:
  - name: detect-concourse
    serial: true
    serial_groups: [ detect ]
    plan:
      - in_parallel:
          - get: concourse-deployment-tag
            trigger: true
          - get: concourse-turbine
          - get: image
          - get: yasak
          - get: gk-automation

      - task: bump-concourse-version
        image: image
        config:
          platform: linux
          inputs:
            - name: concourse-deployment-tag
            - name: concourse-turbine
            - name: yasak
          outputs:
            - name: concourse-turbine-bumped
            - name: bump-info
          caches:
            - path: /usr/local/src/github.com/gstackio/yasak
          run:
            path: bash
            args:
              - -c
              - |
                set -ueo pipefail -x

                # pushd "concourse-turbine-bumped" > /dev/null
                #     go get
                #     make
                #     cp "yasak" "/usr/local/bin"
                # popd > /dev/null

                go get github.com/gstackio/yasak
                sed -i 's|sed -e|sed -i -e|' "yasak/example-edit-value.sh"
                cp "yasak/example-edit-value.sh" "/usr/local/bin/update-yaml-value"

                latest_concourse_tag=$(git -C "concourse-deployment-tag" describe --tags)
                echo "tag: ${latest_concourse_tag}"

                git clone "concourse-turbine" "concourse-turbine-bumped"

                pushd "concourse-turbine-bumped" > /dev/null

                    update-yaml-value \
                        "deployments/concourse/conf/spec.yml" \
                        "/input_resources/name=concourse-deployment/version" \
                        "${latest_concourse_tag}"

                    git config --global "color.ui" "always"
                    git status
                    git diff | cat

                    git config --global "user.name" "((git-commit-name))"
                    git config --global "user.email" "((git-commit-email))"

                    if [[ -z "$(git status --porcelain)" ]]; then
                        echo "INFO: nothing to commit. Skipping."
                    else
                        git add .
                        git commit -m "Bump Concourse to ${latest_concourse_tag}"
                    fi
                popd > /dev/null

      - task: git-push
        image: image
        file: gk-automation/boshrelease/git-push.yml
        input_mapping:
          repo: concourse-turbine-bumped
        params:
          BRANCH_NAME: master
          GIT_URI: ((git_uri))
          GITHUB_PRIVATE_KEY: ((github-private-key))

  - name: detect-os-conf
    serial: true
    serial_groups: [ detect ]
    plan:
      - in_parallel:
          - get: os-conf-bosh-io-release
            trigger: true
            params: { tarball: false }
          - get: concourse-turbine
          - get: image
          - get: yasak
          - get: gk-automation

      - task: bump-os-conf-version
        image: image
        file: concourse-turbine/ci/bump/tasks/bump-bosh-release.yml
        input_mapping:
          bosh-io-release: os-conf-bosh-io-release
          git: concourse-turbine
        params:
          SPEC_FILE: deployments/concourse/conf/spec.yml
          YAML_PROP_PREFIX: os_conf
          RELEASE_HUMAN_NAME: OS Conf BOSH Release
          GIT_COMMIT_NAME: ((git-commit-name))
          GIT_COMMIT_EMAIL: ((git-commit-email))

      - task: git-push
        image: image
        file: gk-automation/boshrelease/git-push.yml
        input_mapping:
          repo: git-bumped
        params:
          BRANCH_NAME: master
          GIT_URI: ((git_uri))
          GITHUB_PRIVATE_KEY: ((github-private-key))

  - name: detect-credhub
    serial: true
    serial_groups: [ detect ]
    plan:
      - in_parallel:
          - get: credhub-bosh-io-release
            trigger: true
            params: { tarball: false }
          - get: concourse-turbine
          - get: image
          - get: yasak
          - get: gk-automation

      - task: bump-credhub-version
        image: image
        file: concourse-turbine/ci/bump/tasks/bump-bosh-release.yml
        input_mapping:
          bosh-io-release: credhub-bosh-io-release
          git: concourse-turbine
        params:
          SPEC_FILE: deployments/concourse/conf/spec.yml
          YAML_PROP_PREFIX: credhub
          RELEASE_HUMAN_NAME: Credhub BOSH Release
          GIT_COMMIT_NAME: ((git-commit-name))
          GIT_COMMIT_EMAIL: ((git-commit-email))

      - task: git-push
        image: image
        file: gk-automation/boshrelease/git-push.yml
        input_mapping:
          repo: git-bumped
        params:
          BRANCH_NAME: master
          GIT_URI: ((git_uri))
          GITHUB_PRIVATE_KEY: ((github-private-key))

  - name: detect-uaa
    serial: true
    serial_groups: [ detect ]
    plan:
      - in_parallel:
          - get: uaa-bosh-io-release
            trigger: true
            params: { tarball: false }
          - get: concourse-turbine
          - get: image
          - get: yasak
          - get: gk-automation

      - task: bump-uaa-version
        image: image
        file: concourse-turbine/ci/bump/tasks/bump-bosh-release.yml
        input_mapping:
          bosh-io-release: uaa-bosh-io-release
          git: concourse-turbine
        params:
          SPEC_FILE: deployments/concourse/conf/spec.yml
          YAML_PROP_PREFIX: uaa
          RELEASE_HUMAN_NAME: UAA BOSH Release
          GIT_COMMIT_NAME: ((git-commit-name))
          GIT_COMMIT_EMAIL: ((git-commit-email))

      - task: git-push
        image: image
        file: gk-automation/boshrelease/git-push.yml
        input_mapping:
          repo: git-bumped
        params:
          BRANCH_NAME: master
          GIT_URI: ((git_uri))
          GITHUB_PRIVATE_KEY: ((github-private-key))


resources:

  - name: image
    type: docker-image
    icon: docker
    source:
      repository: ((docker_ops_image_repo))
      username: ((docker_registry_username))
      password: ((docker-registry-password))

  - name: gk-automation
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/gk-automation.git
      branch: master
      private_key: ((github-private-key))

  - name: concourse-turbine
    type: git
    icon: github
    source:
      uri: ((git_uri))
      branch: master
      private_key: ((github-private-key))

  - name: yasak
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/yasak.git
      branch: master
      private_key: ((github-private-key))

  - name: concourse-deployment-tag
    type: git
    icon: github
    source:
      uri: git@github.com:concourse/concourse-bosh-deployment.git
      branch: master
      tag_filter: ((concourse_version_constraint))
      private_key: ((github-private-key))

  - name: os-conf-bosh-io-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/os-conf-release

  - name: credhub-bosh-io-release
    type: bosh-io-release
    source:
      repository: pivotal-cf/credhub-release

  - name: uaa-bosh-io-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/uaa-release

  # - name: bump-info
  #   type: keyval

resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: harbor.ci.gstack.io/swce/keyval-resource
      username: ((docker_registry_username))
      password: ((docker-registry-password))
