---
platform: linux

image_resource:
  type: registry-image
  source: { repository: gstack/gk-ops }

inputs:
  - name: concourse-turbine # type: git
  - name: github-release    # type: github-release of a BOSH Release project

outputs:
  - name: release-info # a 'properties.yml' file with 'tag', 'version' & 'sha1' values

params:
  BOSH_RELEASE_TABALL: # globs supported
  OUTPUT_FILE_NAME: properties.yml

run:
  path: concourse-turbine/ci/bump/tasks/capture-bosh-release-gh-release-info.sh
